export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
} as const;

export const ROLES = {
  USER: 'user',
  ADMIN: 'admin',
} as const;

export const RESOURCES = {
  TENANT: 'tenant',
  USER: 'user',
} as const;

export const PERMISSIONS = {
  TENANT_CREATE: `${RESOURCES.TENANT}:${ACTIONS.CREATE}`,
  TENANT_READ: `${RESOURCES.TENANT}:${ACTIONS.READ}`,
  TENANT_UPDATE: `${RESOURCES.TENANT}:${ACTIONS.UPDATE}`,
  TENANT_DELETE: `${RESOURCES.TENANT}:${ACTIONS.DELETE}`,

  USER_CREATE: `${RESOURCES.USER}:${ACTIONS.CREATE}`,
  USER_READ: `${RESOURCES.USER}:${ACTIONS.READ}`,
  USER_UPDATE: `${RESOURCES.USER}:${ACTIONS.UPDATE}`,
  USER_DELETE: `${RESOURCES.USER}:${ACTIONS.DELETE}`,
} as const;

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.TENANT_CREATE,
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.TENANT_DELETE,

    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
  ],

  [ROLES.USER]: [
    PERMISSIONS.USER_READ,
  ],
} as const;