worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    upstream api_gateway_nodes {
        server host.docker.internal:3000; 
    }

    upstream api_worker_nodes {
        server host.docker.internal:3001; 
    }

    server {
        listen 80;
        server_name localhost;

	proxy_set_header X-Request-ID $request_id;

        location /api {
            proxy_pass http://api_gateway_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
