version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: fraud_api_gateway
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WORKER_URL=http://api-worker:3001
      - REDIS_URL=redis://fraud_redis:6379
      - KAFKA_BROKER=fraud_kafka:9092
    networks:
      - fraud-network

  api-worker:
    build:
      context: ./api-worker
      dockerfile: Dockerfile
    container_name: fraud_api_worker
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_HOST=fraud_postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=omar
      - DATABASE_PASSWORD=shDs21#eo3kw@
      - DATABASE_NAME=fraud_engine
      - REDIS_URL=redis://fraud_redis:6379
    networks:
      - fraud-network
