version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: fraud_nginx_dev
    restart: always
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../reverse-proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - fraud-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fraud_zookeeper_dev
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fraud-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fraud_kafka_dev
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - fraud-network

  postgres:
    image: postgres:15-alpine
    container_name: fraud_postgres_dev
    restart: always
    env_file:
      - ./secrets/secrets.dev.txt
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - fraud-network

  redis:
    image: redis:7-alpine
    container_name: fraud_redis_dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/var/lib/redis/data
    networks:
      - fraud-network

  neo4j:
    image: neo4j:latest
    container_name: fraud_graph_db_dev
    restart: always
    env_file:
      - ./secrets/secrets.dev.txt
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_dev_data:/data
      - neo4j_dev_plugins:/plugins
    networks:
      - fraud-network

networks:
  fraud-network:
    driver: bridge

volumes:
  postgres_dev_data:
  redis_dev_data:
  neo4j_dev_data:
  neo4j_dev_plugins:
