version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fraud_postgres
    restart: always
    environment:
      POSTGRES_USER: fraud_admin
      POSTGRES_PASSWORD: super_secure_password_2026
      POSTGRES_DB: fraud_detection_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fraud-network

  redis:
    image: redis:7-alpine
    container_name: fraud_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - fraud-network

volumes:
  postgres_data:
  redis_data:
