version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: fraud_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - fraud-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fraud_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fraud-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fraud_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - fraud-network
  
  postgres:
    image: postgres:15-alpine
    container_name: fraud_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Hsa@AUFS32!R
      POSTGRES_DB: fraud_detection_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fraud-network

  redis:
    image: redis:7-alpine
    container_name: fraud_redis
    restart: always
    networks:
      - fraud-network
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - fraud-network

volumes:
  postgres_data:
  redis_data:
