version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: fraud_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../reverse-proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    networks:
      - fraud-network

  certbot:
    image: certbot/certbot
    container_name: fraud_certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
  kafka:
    image: apache/kafka:3.9.0
    container_name: fraud_kafka_dev
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: fraud-kafka-cluster-1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - fraud-network

  postgres:
    image: postgres:15-alpine
    container_name: fraud_postgres
    restart: always
    env_file:
      - ./secrets/secrets.prod.txt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fraud-network

  redis:
    image: redis:7-alpine
    container_name: fraud_redis
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - fraud-network

  neo4j:
    image: neo4j:latest
    container_name: fraud_graph_db
    restart: always
    env_file:
      - ./secrets/secrets.prod.txt
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    networks:
      - fraud-network

networks:
  fraud-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  neo4j_plugins:
  certbot_etc:
  certbot_var:
  kafka_data:
